// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger Bookshelf
This is a sample server Bookshelf server. 本棚アプリケーションのサンプル。

Terms Of Service:

http://www.example.com/terms/


    Schemes:
      http
      https
    Host: www.example.com
    BasePath: /v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <hoge@example.com>

    Consumes:
    - application/json
    - application/x-www-form-urlencoded
    - application/xml

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
