// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddBookMethodNotAllowedCode is the HTTP code returned for type AddBookMethodNotAllowed
const AddBookMethodNotAllowedCode int = 405

/*AddBookMethodNotAllowed Invalid input

swagger:response addBookMethodNotAllowed
*/
type AddBookMethodNotAllowed struct {
}

// NewAddBookMethodNotAllowed creates AddBookMethodNotAllowed with default headers values
func NewAddBookMethodNotAllowed() *AddBookMethodNotAllowed {

	return &AddBookMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddBookMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
