// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteBookHandlerFunc turns a function with the right signature into a delete book handler
type DeleteBookHandlerFunc func(DeleteBookParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBookHandlerFunc) Handle(params DeleteBookParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteBookHandler interface for that can handle valid delete book params
type DeleteBookHandler interface {
	Handle(DeleteBookParams, interface{}) middleware.Responder
}

// NewDeleteBook creates a new http.Handler for the delete book operation
func NewDeleteBook(ctx *middleware.Context, handler DeleteBookHandler) *DeleteBook {
	return &DeleteBook{Context: ctx, Handler: handler}
}

/*DeleteBook swagger:route DELETE /book/{bookId} book deleteBook

Deletes a book

*/
type DeleteBook struct {
	Context *middleware.Context
	Handler DeleteBookHandler
}

func (o *DeleteBook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteBookParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
