// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateBookBadRequestCode is the HTTP code returned for type UpdateBookBadRequest
const UpdateBookBadRequestCode int = 400

/*UpdateBookBadRequest Invalid ID supplied

swagger:response updateBookBadRequest
*/
type UpdateBookBadRequest struct {
}

// NewUpdateBookBadRequest creates UpdateBookBadRequest with default headers values
func NewUpdateBookBadRequest() *UpdateBookBadRequest {

	return &UpdateBookBadRequest{}
}

// WriteResponse to the client
func (o *UpdateBookBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateBookNotFoundCode is the HTTP code returned for type UpdateBookNotFound
const UpdateBookNotFoundCode int = 404

/*UpdateBookNotFound Book not found

swagger:response updateBookNotFound
*/
type UpdateBookNotFound struct {
}

// NewUpdateBookNotFound creates UpdateBookNotFound with default headers values
func NewUpdateBookNotFound() *UpdateBookNotFound {

	return &UpdateBookNotFound{}
}

// WriteResponse to the client
func (o *UpdateBookNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateBookMethodNotAllowedCode is the HTTP code returned for type UpdateBookMethodNotAllowed
const UpdateBookMethodNotAllowedCode int = 405

/*UpdateBookMethodNotAllowed Validation exception

swagger:response updateBookMethodNotAllowed
*/
type UpdateBookMethodNotAllowed struct {
}

// NewUpdateBookMethodNotAllowed creates UpdateBookMethodNotAllowed with default headers values
func NewUpdateBookMethodNotAllowed() *UpdateBookMethodNotAllowed {

	return &UpdateBookMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateBookMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
