// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateBookWithFormMethodNotAllowedCode is the HTTP code returned for type UpdateBookWithFormMethodNotAllowed
const UpdateBookWithFormMethodNotAllowedCode int = 405

/*UpdateBookWithFormMethodNotAllowed Invalid input

swagger:response updateBookWithFormMethodNotAllowed
*/
type UpdateBookWithFormMethodNotAllowed struct {
}

// NewUpdateBookWithFormMethodNotAllowed creates UpdateBookWithFormMethodNotAllowed with default headers values
func NewUpdateBookWithFormMethodNotAllowed() *UpdateBookWithFormMethodNotAllowed {

	return &UpdateBookWithFormMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateBookWithFormMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
